Models/ErrorViewModel.cs
namespace tp4Routing.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Produit.cs
namespace tp4Routing.Models
{
    public class Produit
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal PrixUnitaire { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tp4Routing.Models;

namespace tp4Routing.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProduitController.cs
using Microsoft.AspNetCore.Mvc;
using tp4Routing.Models;

namespace tp4Routing.Controllers
{
    public class ProduitController : Controller
    {
       static List<Produit> produits = new List<Produit>
        {
            new Produit { Id = 1, Description = "Produit 1", PrixUnitaire = 10.99m },
            new Produit { Id = 2, Description = "Produit 2", PrixUnitaire = 15.99m },
            new Produit { Id = 3, Description = "Produit 3", PrixUnitaire = 8.49m }

        };

        //routing par attributs
        [Route("/")]
        [Route("Accueil")]
        [Route("Accueil/Index")]
        public IActionResult Accueil()
        {
            ViewBag.ProduitsList = produits;
            return View();
        }
        //public IActionResult ListProduits()
        //{
        //    return View();
        //}

        [Route("Edit")]
        [Route("Edit/{id:int}")]
        public IActionResult Edit(int Id)
        {
            return View(produits[Id-1]);
        }

        [Route("Update")]
        [Route("Update/{id:int}")]
        public IActionResult Update(Produit produit)
        {
           // ViewBag.ProduitsList = produits;
            var product = produits.Find(p => p.Id == produit.Id);
            product.Description = produit.Description ;
            return RedirectToAction("Lister");
        }

        [Route("Lister")]
        [Route("Lister/{id:int}")]
        public IActionResult Lister()
        {
            ViewBag.ProduitsList = produits;
            return View();
        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Produit/Accueil.cshtml
@{
    ViewData["Title"] = "Accueil Page";
}
<div>
    <h1>Accueil Page</h1>
</div>

<a asp-controller="Produit" asp-action="Lister">Lien ICI</a>
<br />

<h5>list des IDs</h5>
<ul>
    @foreach(var item in ViewBag.ProduitsList)
    {
        <li><a asp-route-Id=@item.Id asp-action="Edit">ID</a></li>
    }
</ul>

Views/Produit/Edit.cshtml
@model tp4Routing.Models.Produit

@{
    ViewData["Title"] = "Edit Product";
}

<h1>Edit Product</h1>

<form asp-controller="Produit" asp-action="Update" method="post">
    <input type="Text" asp-for="Id" readonly />

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="PrixUnitaire"></label>
        <input asp-for="PrixUnitaire" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Update Product</button>
</form>

<a asp-controller="Produit" asp-action="Lister">Back to List</a>

Views/Produit/Lister.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h1>Lister Page</h1>
</div>


<ul>
    @foreach (var item in ViewBag.ProduitsList)
    {
        <li>@item.Id - @item.Description</li>
    }
</ul>

<a asp-controller="Produit" asp-action="Accueil">Back to accueil</a>

Views/Produit/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h1>Update Page</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tp4Routing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tp4Routing.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tp4Routing</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tp4Routing - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>